-- Isolation
-- Pages and Rows versions
-- DATA SNAPSHOTS
-- Hot-updates and Innerpage's cleaning


-------ISOLATION LEVELS----------------------------

CREATE TABLE accounts(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    client text,
    amount numeric
);
INSERT INTO accounts VALUES
(1, 'alice', 1000.00),
(2, 'bob', 100.00),
(3, 'bob', 900.00);







----------------PAGES and ROW VERSIONS-------------------------





CREATE EXTENSION pageinspect;



--sizes of secions of the page
SELECT lower, upper, special, pagesize
FROM page_header(get_raw_page('accounts', 0));

CREATE TABLE padding(
    b1 boolean,
    i1 integer,
    b2 boolean,
    i2 integer
);
INSERT INTO padding VALUES (true, 1, false, 2);
SELECT lp_len FROM heap_page_items(get_raw_page('padding', 0)); -- 40

DROP TABLE padding;
CREATE TABLE padding(
    i1 integer,
    i2 integer,
    b1 boolean,
    b2 boolean
);
INSERT INTO padding VALUES (1,2,true,false);
SELECT lp_len FROM heap_page_items(get_raw_page('padding', 0));




-------------------OPERATIONS ON THE STRINGS LEVELS------------------




CREATE TABLE t(
    id integer GENERATED ALWAYS AS IDENTITY,
    s TEXT
);
CREATE INDEX ON t(s);

--------------------------INSERT---------------

BEGIN;
INSERT INTO t(s) VALUES ('FOO');


-- xact - number of a transaction
SELECT pg_current_xact_id();

-- one command
SELECT * FROM heap_page_items(get_raw_page('t', 0))
\gx

SELECT '(0,'||lp||')' as ctid,
    CASE lp_flags
        WHEN 0 THEN 'unused'
        WHEN 1 THEN 'normal'
        WHEN 2 then 'redirect to '||lp_off
        WHEN 3 THEN 'dead'
    END AS state,
    t_xmin as xmin,
    t_xmax as xmax,
    (t_infomask & 256) > 0 AS xmin_commited,
    (t_infomask & 512) > 0 AS xmin_aborted,
    (t_infomask & 1024) > 0 AS xmax_committed,
    (t_infomask & 2048) > 0 AS xmax_aborted
FROM heap_page_items(get_raw_page('t', 0))
\gx




-- this function shows information about row
-- ctid, state, xmin, xmax -- (xmin(insert), xmax(delete) - transactions)
CREATE FUNCTION heap_page(relname text, pageno integer)
RETURNS TABLE (ctid tid, state text, xmin text, xmax text)
AS $$
SELECT (pageno, lp)::text::tid AS ctid,
    CASE lp_flags
        WHEN 0 THEN 'unused'
        WHEN 1 THEN 'normal'
        WHEN 2 then 'redirect to '||lp_off
        WHEN 3 THEN 'dead'
    END AS state,
    t_xmin || CASE
        WHEN (t_infomask & 256) > 0 THEN ' c'   -- committed
        WHEN (t_infomask & 512) > 0 THEN ' a'   -- aborted
        ELSE ''
    END AS xmin,
    t_xmax || CASE
        WHEN (t_infomask & 1024) > 0 THEN ' c'
        WHEN (t_infomask & 2048) > 0 THEN ' a'
    END AS xmax
FROM heap_page_items(get_raw_page(relname, pageno))
ORDER BY lp;
$$ LANGUAGE sql;




SELECT * FROM heap_page('t',0);
SELECT xmin, xmax, * FROM t;

COMMIT;


-------------------FIXATION-----------------------



SELECT * FROM heap_page('t', 0); -- nothing happened
SELECT * FROM t;
SELECT * FROM heap_page('t', 0); -- xmin => c (committed)


--------------------DELETING----------------------

BEGIN;
DELETE FROM t;
SELECT pg_current_xact_id();

SELECT * FROM heap_page('t', 0); -- xmax - _


--------------------CANCELING---------------------

ROLLBACK;
SELECT * FROM heap_page('t', 0);  -- xmax - _

SELECT * FROM t;

SELECT * FROM heap_page('t', 0); -- xmax - a (aborted)


-------------------UPDATING-----------------------
BEGIN;
UPDATE t SET s = 'BAR';
SELECT pg_current_xact_id();     -- 938

SELECT * FROM t;
SELECT * FROM heap_page('t', 0); -- xmin -> 938

COMMIT;

SELECT * FROM t;
SELECT * FROM heap_page('t', 0); 
-- 0, 1 xmax - 938 c and 0, 2 xmin -> 938 c
-- because previous transaction was canceled


--------------INDEXES--------------------------------------





CREATE FUNCTION index_page(relname text, pageno integer)
RETURNS TABLE(itemoffset smallint, htid tid)
AS $$
SELECT itemoffset, htid
FROM bt_page_items(relname, pageno);
$$ LANGUAGE sql;





SELECT * FROM index_page('t_s_idx', 1);


--------------VIRTUAL TRANSACTIONS--------------------


BEGIN;
SELECT pg_current_xact_id_if_assigned(); -- _ there isn't real transaction number

UPDATE accounts
SET amount = amount - 1;
SELECT pg_current_xact_id_if_assigned();    -- 940 it's a real transaction
COMMIT;


--------------NESTED TRANSACTIONS-------------------

TRUNCATE TABLE t;
BEGIN;
INSERT INTO t(s) VALUES ('FOO');
SELECT pg_current_xact_id();    -- 942 id of the main transaction

SAVEPOINT sp;
INSERT INTO t(s) VALUES ('XYZ');
SELECT pg_current_xact_id();    -- 942

SELECT * FROM heap_page('t', 0) p
LEFT JOIN t ON p.ctid = t.ctid;

ROLLBACK TO sp;
INSERT INTO t(s) VALUES ('BAR');
-- there, we have (0, 2) transaction, without id and s from t
SELECT * FROM heap_page('t', 0) p 
LEFT JOIN t ON p.ctid = t.ctid;

COMMIT;
SELECT * FROM t;
SELECT * FROM heap_page('t', 0);    -- (0, 2) is in the query, but aborted

----------------------ERRORS HANDLING------------------------

BEGIN;
SELECT * FROM t;
UPDATE t SET s = repeat('X', 1/(id-4)); -- error

SELECT * FROM heap_page('t', 0);

--  \set ON_ERROR_ROLLBACK on  ---------!!
BEGIN;
UPDATE t SET s = repeat('X', 1/(id-4));
SELECT * FROM t;
COMMIT;









--------------------DATA SNAPSHOTS------------------------------------





TRUNCATE TABLE accounts;

BEGIN;
INSERT INTO accounts VALUES (1, 'alice', 1000);
SELECT pg_current_xact_id();    -- 949

-- second transactions
-- BEGIN;
-- INSERT INTO accounts VALUES (2, 'bob', 100);
-- SELECT pg_current_xact_id();    -- 951
-- COMMIT;

--- third
--- BEGIN ISOLATION LEVEL REPEATABLE READ;
--- SELECT pg_current_snapshot();  -- !!   949:953:949

COMMIT;

-- second
-- BEGIN;
-- UPDATE accounts SET amount = amount + 100 WHERE id = 2;
-- SELECT pg_current_xact_id();        --953
-- COMMIT;

--- third
--- SELECT ctid, * FROM accounts;
--- SELECT * FROM heap_page('accounts', 0);
--- COMMIT;


-- 954 - error
BEGIN;
INSERT INTO accounts VALUES (3, 'charlie', 100);
SELECT pg_current_xact_id();    -- 955

DECLARE c CURSOR FOR SELECT count(*) FROM accounts;
INSERT INTO accounts VALUES (4, 'charlie', 200);

SELECT xmin,
    CASE WHEN xmin = 955 THEN cmin END
    cmin, *
FROM accounts; -- 3 strings

FETCH c;    -- 3


-----------------HORIZON of TRANSACTIONS--------------


BEGIN;
SELECT backend_xmin FROM pg_stat_activity
WHERE pid = pg_backend_pid();       -- 954

-- second
-- SELECT pg_current_xact_id();        -- 957

SELECT backend_xmin FROM pg_stat_activity
WHERE pid = pg_backend_pid();       -- 954

COMMIT;
SELECT backend_xmin FROM pg_stat_activity
WHERE pid = pg_backend_pid();



BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SELECT 1;       -- create the snapshot for the transaction

-- second
-- ALTER TABLE accounts ALTER amount SET NOT NULL;

INSERT INTO accounts(client, amount) VALUES ('alice', NULL); -- error, not null constraint
ROLLBACK;



-------------------EXPORT DATA SNAPSHOT-----------------
BEGIN ISOLATION  LEVEL REPEATABLE READ;
SELECT count(*) FROM accounts;      -- 4
SELECT pg_export_snapshot();        -- 00000009-00000013-1

-- second
-- DELETE FROM accounts;
-- BEGIN ISOLATION LEVEL REPEATABLE READ;
-- SET TRANSACTION SNAPSHOT '00000009-00000013-1';
-- SELECT count(*) FROM accounts;      -- 4
-- COMMIT;

COMMIT;








---------------INNERPAGE CLEANING--------------------------
CREATE TABLE hot(id integer, s char(2000)) WITH (fillfactor = 75);
CREATE INDEX hot_id ON hot(id);
CREATE INDEX hot_s ON hot(s);
INSERT INTO hot VALUES (1, 'A');
UPDATE hot SET s = 'B';
UPDATE hot SET s = 'C';
UPDATE hot SET s = 'D';
SELECT * FROM heap_page('hot', 0);

-- we have taken more than fillfactor = 75
SELECT upper, pagesize FROM page_header(get_raw_page('hot', 0));

UPDATE hot SET s = 'E';
SELECT * FROM heap_page('hot', 0); -- 4 and on the page 1 (1,1)

SELECT * FROM index_page('hot_s', 1); -- 5 itemoffsets

SELECT * FROM index_page('hot_id', 1);  -- 5






DROP FUNCTION index_page(text, integer);
CREATE FUNCTION index_page(relname text, pageno integer)
RETURNS TABLE (itemoffset smallint, htid tid, dead boolean)
AS $$
SELECT itemoffset, htid, dead
FROM bt_page_items(relname, pageno);
$$ LANGUAGE sql;




SELECT * FROM index_page('hot_id', 1);      -- dead - false (for all)

EXPLAIN (analyze, costs off, timing off, summary off)
SELECT * FROM hot WHERE id = 1;
SELECT * FROM index_page('hot_id', 1);




---------------------HOT-UPDATES------------------------------




DROP INDEX hot_s;
TRUNCATE TABLE hot;

DROP FUNCTION heap_page(text, integer);





CREATE FUNCTION heap_page(relname text, pageno integer)
RETURNS TABLE (ctid tid, state text, xmin text,
                xmax text, hhu text, hot text,
                t_ctid tid) AS $$
SELECT (pageno, lp)::text::tid AS ctid,
    CASE lp_flags
        WHEN 0 THEN 'unused'
        WHEN 1 THEN 'normal'
        WHEN 2 THEN 'redirect to '||lp_off
        WHEN 3 THEN 'dead'
    END AS state,
    t_xmin || CASE
        WHEN (t_infomask & 256) > 0 THEN ' c'
        WHEN (t_infomask & 512) > 0 THEN ' a'
    END AS xmin,
    t_xmax || CASE
        WHEN (t_infomask & 1024) > 0 THEN ' c'
        WHEN (t_infomask & 2048) > 0 THEN ' a'
        ELSE ''
    END AS xmax,
    CASE WHEN (t_infomask2 & 16384) > 0 THEN 't' END AS hhu,
    CASE WHEN (t_infomask2 & 32768) > 0 THEN 't' END AS hot,
    t_ctid      -- show the link of ctid's for Heap Hot Updated optimization concept
FROM heap_page_items(get_raw_page(relname, pageno))
ORDER BY lp;
$$ LANGUAGE sql;



INSERT INTO hot VALUES (1, 'A');
UPDATE hot SET s = 'B';

SELECT * FROM heap_page('hot', 0);

UPDATE hot SET s = 'C';
UPDATE hot SET s = 'D';
SELECT * FROM heap_page('hot', 0);

SELECT * FROM index_page('hot_id', 1);

SELECT n_tup_upd, n_tup_hot_upd
FROM pg_stat_all_tables
WHERE relid = 'hot'::regclass;



UPDATE hot SET s = 'E';
SELECT * FROM heap_page('hot', 0);

UPDATE hot SET s = 'F';
UPDATE hot SET s = 'G';
SELECT * FROM heap_page('hot', 0);


UPDATE hot SET s = 'H';
SELECT * FROM heap_page('hot', 0);

-- link will be growing and come to the next page,
-- new link will be added in index_page(on the 1,1)



-- second
-- BEGIN ISOLATION LEVEL REPEATABLE READ;
-- SELECT 1;

-- first
UPDATE hot SET s = 'I';
UPDATE hot SET s = 'J';
UPDATE hot SET s = 'K';
SELECT * FROM heap_page('hot', 0); -- 3 pages (0, 1, 2)
UPDATE hot SET s = 'J';


-- second
-- COMMIT;

-- first
SELECT * FROM heap_page('hot', 0);
SELECT * FROM heap_page('hot', 1);
SELECT * FROM heap_page('hot', 2);
SELECT * FROM index_page('hot_id', 1); -- 3 links

SELECT n_tup_upd, n_tup_hot_upd, n_tup_ins
FROM pg_stat_all_tables
WHERE relid = 'hot'::regclass
\gx

-- we have 15 update operations: 11 - hot(2 on the next pages), 4 - are not hot

